---
# - name: Printing all the environmentâ€‹ variables in Ansible transmission
#   debug:
#     msg: "{{ ansible_env }}"
#     #msg: "{{ lookup('env','MYGLOBAL','HOME','SHELL') }}"

- name: 44 Debug transmission_namespace variable
  debug:
    var: transmission_namespace 

- name: Check if Namespace Exists
  include_tasks: create_namespace.yml
 
- name: Persistant volume claim
  include_tasks: transmission_pvc.yml

- name: Transmission container
  include_tasks: transmission_container.yml
